title: TeamImagine
description: 用扯淡的心情认真生活~
keywords: "JavaScript, Node, CSS, HTML, HTML5, PDF, PPT, design, ued"
url: "https://teamimagine.github.io/"

author:
  name: MurphyL
  email: im@cijian.us
  weibo: MurphyLuo
  github: MurphyL
  twitter: MurphyLuo

# Staticman
staticman:
 allowedFields: ['title', 'description']
 branch: test
 commitMessage: "Hey human, here is a new entry."
 filename: "entry{@timestamp}"
 format: yml
 moderation: true
 path: "_data/reviews"
 requiredFields: ['title', 'description']